version: 0.2
phases:
  install:
    commands:      
      - "npm install -g yarn"
      - "yarn install"
  pre_build:
    commands:
      - "yarn run build" 
      - yarn build-storybook -o         
  build:
    commands:
      - echo "build complete"
artifacts:
  files:
    - "*/"
