version: 0.2

phases:
  install:
    commands:
      - echo update npm...
      - npm install 
      - echo install yarn...
      - npm install -g yarn
      - echo yarn -v
      - yarn -v
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - yarn run dev
      - yarn run test
      - yarn run build
      - echo "build complete"
artifacts:
  files:
    - "*/"
