version: 0.2
phases:
  install:
    commands:
      - yarn install
      - yarn add -g typescript
  pre_build:
    commands:
      - CI= yarn run build 
      - yarn build-storybook -o         
  build:
    commands:
      - echo "build complete"
artifacts:
  files:
    - "*/"
