version: 0.2
phases:
  install:
    commands:
      - yarn install
  pre_build:
    commands:
      - yarn build 
      - yarn build storybook         
  build:
    commands:
      - echo "build complete"
artifacts:
  files:
    - "*/"
