version: 0.2
phases:
  install:
    commands:
      - yarn install
  pre_build:
    commands:
      - yarn build storybook
      - yarn run build    
  build:
    commands:
      
artifacts:
  files:
    - "*/"
