version: 0.2
phases:
  install:
    commands:
      - npm install -g lerna
  pre_build:
    commands:
      - lerna --no-ci --concurrency 4
  build:
    commands:
      - lerna run build --concurrency 4
artifacts:
  files:
    - "*/"
