version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source yarn dependencies...
      - yarn install
      - yarn global add typescript
      - yarn install node-sass
  build:
    commands:
      - echo Build started on `date`
      - yarn build
      - echo Compiling the dist folder    
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - index.js
    - dist/**/*
    - request-map.js
    - credentials.json
    - node_modules/**/*
